### ISSUE TITLE
QuteScoop quit unexpectedly on macOS

### ISSUE THREAD

**Issue by jorgeuvo** [qutescoop/qutescoop#180] opened 2023-01-30 16:57 UTC
I have installed the version 2.7.1 and it is giving the error "QuteScoop quit unexpectedly" when trying to open in. I am on macOS Ventura 13.1, M1 processor.

It is a known issue? Any help?

See below the full report of the error.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               QuteScoop [16712]
Path:                  /private/var/folders/*/QuteScoop.app/Contents/MacOS/QuteScoop
Identifier:            com.yourcompany.QuteScoop
Version:               ???
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-01-30 11:51:48.2818 -0500
OS Version:            macOS 13.1 (22C65)
Report Version:        12
Anonymous UUID:        AD9B7A35-9F8D-C1D3-C9A4-6A7C8A7A9181

Sleep/Wake UUID:       CEFA5BAF-66BA-4143-8E59-08AD72C4D968

Time Awake Since Boot: 100000 seconds
Time Since Wake:       847 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/QtOpenGL.framework/Versions/5/QtOpenGL
Referenced from: <F37FB768-8F91-396D-AF7B-6BA08798B659> /private/var/folders/*/QuteScoop.app/Contents/MacOS/QuteScoop
Reason: tried: '/private/var/folders/ls/xxc_3mfj4v55h85v3frklxkr0000gn/T/AppTranslocation/B6933134-AE91-4E08-A7A1-56CBDC87216F/d/QuteScoop.app/Contents/Frameworks/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/Users/runner/work/qutescoop/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/qutescoop/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/private/var/folders/ls/xxc_3mfj4v55h85v3frklxkr0000gn/T/AppTranslocation/B6933134-AE91-4E08-A7A1-56CBDC87216F/d/QuteScoop.app/Contents/Frameworks/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/Users/runner/work/qutescoop/Qt/5.15.2/clang_64/lib/QtOpenGL.framew
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x102fa89a8 ???
1   <translation info unavailable>	       0x1030349b4 ???
2   dyld                          	       0x20306cd07 abort_with_payload_wrapper_internal + 82
3   dyld                          	       0x20306cd39 abort_with_payload + 9
4   dyld                          	       0x202ff41e1 dyld4::halt(char const*) + 375
5   dyld                          	       0x202ff1660 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4502
6   dyld                          	       0x202ff0281 start + 2289

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffc12614 0x7ff7ffc0e000 + 17940
1   runtime                       	    0x7ff7ffc1e530 0x7ff7ffc0e000 + 66864
2   runtime                       	    0x7ff7ffc1ff30 0x7ff7ffc0e000 + 73520

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x0000000309d32910   x3: 0x00000000000000da
    x4: 0x0000000309d32510   x5: 0x0000000000000000   x6: 0x0000000309d328e0   x7: 0x0000002002ff6844
    x8: 0x0000000309d32510   x9: 0x0000000000000000  x10: 0x00000000000000da  x11: 0x0000000309d32510
   x12: 0x00000000000000da  x13: 0x0000000309d32910  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x800000010b009b80  x19: 0x0000000102f9e000
   x20: 0x00000000000007ff  x21: 0x000000010b00efa0  x22: 0xffffffffffffffff  x23: 0x0000000102fa897c
   x24: 0x000000020306cd07  x25: 0x0000000102fa8248  x26: 0x0000000103032520  x27: 0x0000000000000000
   x28: 0x0000000203053b4a   fp: 0x000000002c000000   lr: 0x00000001030349b4
    sp: 0x000000010b009b80   pc: 0x0000000102fa89a8 cpsr: 0x80001000
   far: 0x0000000103034000  esr: 0x56000080  Address size fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x202fea000 -        0x203081fff dyld (*) <bb7a0970-8c62-3dce-a7a2-5cec9c501f11> /usr/lib/dyld
    0x7ff7ffc0e000 -     0x7ff7ffc3dfff runtime (*) <d592bc4a-4a21-348f-a406-e12f9cd2f27c> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=3032K resident=0K(0%) swapped_out_or_unallocated=3032K(100%)
Writable regions: Total=156.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=156.9M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    892K      220 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       15.4M        7 
VM_ALLOCATE (reserved)              32K        1         reserved VM address space (unallocated)
__DATA                             160K        6 
__DATA_CONST                        32K        1 
__DATA_DIRTY                        16K        1 
__LINKEDIT                         720K        8 
__TEXT                            2352K        4 
dyld private memory                512K        2 
mapped file                        6.6G       40 
===========                     =======  ======= 
TOTAL                              6.8G      300 
TOTAL, minus reserved VM space     6.8G      300 

-----------
Full Report
-----------

{"app_name":"QuteScoop","timestamp":"2023-01-30 11:51:48.00 -0500","app_version":"","slice_uuid":"f37fb768-8f91-396d-af7b-6ba08798b659","build_version":"","platform":1,"bundleID":"com.yourcompany.QuteScoop","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.1 (22C65)","roots_installed":0,"name":"QuteScoop","incident_id":"F993B8C0-A092-4791-BBDA-65F490152AF0"}
{
  "uptime" : 100000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,4",
  "coalitionID" : 9116,
  "osVersion" : {
    "train" : "macOS 13.1",
    "build" : "22C65",
    "releaseType" : "User"
  },
  "captureTime" : "2023-01-30 11:51:48.2818 -0500",
  "incident" : "F993B8C0-A092-4791-BBDA-65F490152AF0",
  "pid" : 16712,
  "translated" : true,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-01-30 11:51:48.1423 -0500",
  "procStartAbsTime" : 2519891854167,
  "procExitAbsTime" : 2519895191669,
  "procName" : "QuteScoop",
  "procPath" : "\/private\/var\/folders\/*\/QuteScoop.app\/Contents\/MacOS\/QuteScoop",
  "bundleInfo" : {"CFBundleIdentifier":"com.yourcompany.QuteScoop"},
  "storeInfo" : {"deviceIdentifierForVendor":"D69D4F9C-E309-505C-9A71-AE69578E8757","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.yourcompany.QuteScoop",
  "crashReporterKey" : "AD9B7A35-9F8D-C1D3-C9A4-6A7C8A7A9181",
  "throttleTimeout" : 2147483647,
  "wakeTime" : 847,
  "sleepWakeUUID" : "CEFA5BAF-66BA-4143-8E59-08AD72C4D968",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/QtOpenGL.framework\/Versions\/5\/QtOpenGL","Referenced from: <F37FB768-8F91-396D-AF7B-6BA08798B659> \/private\/var\/folders\/*\/QuteScoop.app\/Contents\/MacOS\/QuteScoop","Reason: tried: '\/private\/var\/folders\/ls\/xxc_3mfj4v55h85v3frklxkr0000gn\/T\/AppTranslocation\/B6933134-AE91-4E08-A7A1-56CBDC87216F\/d\/QuteScoop.app\/Contents\/Frameworks\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/Users\/runner\/work\/qutescoop\/Qt\/5.15.2\/clang_64\/lib\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/Users\/runner\/work\/qutescoop\/Qt\/5.15.2\/clang_64\/lib\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/private\/var\/folders\/ls\/xxc_3mfj4v55h85v3frklxkr0000gn\/T\/AppTranslocation\/B6933134-AE91-4E08-A7A1-56CBDC87216F\/d\/QuteScoop.app\/Contents\/Frameworks\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/Users\/runner\/work\/qutescoop\/Qt\/5.15.2\/clang_64\/lib\/QtOpenGL.framew"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":880268,"threadState":{"x":[{"value":6},{"value":1},{"value":13049735440},{"value":218},{"value":13049734416},{"value":0},{"value":13049735392},{"value":137489246276},{"value":13049734416},{"value":0},{"value":218},{"value":13049734416},{"value":218},{"value":13049735440},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041334332288},{"value":4344897536},{"value":2047},{"value":4479578016},{"value":18446744073709551615},{"value":4344940924},{"value":8640711943,"symbolLocation":82,"symbol":"abort_with_payload_wrapper_internal"},{"value":4344939080},{"value":4345505056},{"value":0},{"value":8640609098,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4345514420},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4479556480},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4344940968,"matchesCrashFrame":1},"far":{"value":4345511936}},"frames":[{"imageOffset":4344940968,"region":"Rosetta Runtime Routines","symbolLocation":10664,"imageIndex":0},{"imageOffset":4345514420,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":535815,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":1},{"imageOffset":535865,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":41441,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":30304,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4502,"imageIndex":1},{"imageOffset":25217,"symbol":"start","symbolLocation":2289,"imageIndex":1}]},{"id":880286,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":17940,"imageIndex":2},{"imageOffset":66864,"imageIndex":2},{"imageOffset":73520,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8640176128,
    "size" : 622592,
    "uuid" : "bb7a0970-8c62-3dce-a7a2-5cec9c501f11",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703124480000,
    "size" : 196608,
    "uuid" : "d592bc4a-4a21-348f-a406-e12f9cd2f27c",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703373754368,
  "size" : 21474836480,
  "uuid" : "16923f88-e9fc-38d2-947c-df242e486636"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=3032K resident=0K(0%) swapped_out_or_unallocated=3032K(100%)\nWritable regions: Total=156.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=156.9M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    892K      220 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       15.4M        7 \nVM_ALLOCATE (reserved)              32K        1         reserved VM address space (unallocated)\n__DATA                             160K        6 \n__DATA_CONST                        32K        1 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                         720K        8 \n__TEXT                            2352K        4 \ndyld private memory                512K        2 \nmapped file                        6.6G       40 \n===========                     =======  ======= \nTOTAL                              6.8G      300 \nTOTAL, minus reserved VM space     6.8G      300 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000026
    },
    {
      "rolloutId" : "61675b89201f677a9a4cbd65",
      "factorPackIds" : {
        "HEALTH_FEATURE_AVAILABILITY" : "638e768d75b0720ff1f8c4f3"
      },
      "deploymentId" : 240000051
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,4, BootROM 8419.60.44, proc 10:8:2 processors, 64 GB, SMC 
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Display: LEN T24i-10, 1920 x 1080 (1080p FHD - Full High Definition), MirrorOff, Online
Display: P24q-10, 2560 x 1440 (QHD/WQHD - Wide Quad High Definition), MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Sep  3 2022 02:35:52 version 20.10.965.9.8.7.129 FWID 01-b0e84a9b
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB3.1 Hub
USB Device: USB 10/100/1000 LAN
USB Device: USB2.1 Hub
USB Device: Apple Watch Magnetic Charging Cable
USB Device: USB 2.0 Hub
USB Device: USB C Video Adaptor
USB Device: USB31Bus
USB Device: USB3.0 Hub
USB Device: USB3.0 Hub
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
USB Device: Bravo Throttle Quadrant
USB Device: Saitek Pro Flight Rudder Pedals
USB Device: Alpha Flight Controls
USB Device: USB2.1 Hub
USB Device: USB Receiver
USB Device: Jabra UC VOICE 550a MS
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by jonaseberle** [comment] 2023-01-30 17:33
Hi @jorgeuvo, we don't have working Mac builds AFAIK and especially we never tried to build for Mac M1. 

Duplicate of https://github.com/qutescoop/qutescoop/issues/134

**Comment by jonaseberle** [comment] 2023-02-02 09:40
Closing in favor of https://github.com/qutescoop/qutescoop/issues/48.

The Mac community has to step up if you want Mac builds.

**Closed as completed by jonaseberle** 2023-02-02 09:40 UTC
